### ISSUE TITLE
Support for pydantic v2

### ISSUE THREAD

**Issue by max-radin** [amazon-braket/amazon-braket-default-simulator-python#212]
**Describe the feature you'd like**
Support for at least one `2.X.X` version of pydantic.

**How would this feature be used? Please describe.**
Adding support for [pydantic v2](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/) would allow us to upgrade [orquestra-sdk](https://github.com/zapatacomputing/orquestra-sdk) to also use pydantic v2 and benefit from the improvements it offers. 

The reason for this is that the [orquestra-core metapackage](https://github.com/zapatacomputing/orquestra-core) depends on pydantic transitively through orquestra-sdk as well as amazon-braket-default-simulator and amazon-braket-schemas-python. So currently, upgrading orquestra-sdk to pydantic v2 would create a dependency conflict for orquestra-core.

**Describe alternatives you've considered**
Our current strategy is to continue using `pydantic < 2.0.0`.

**Comment by guomanmin** [comment]
Hi @max-radin - thanks for raising this, we're looking at a couple of options before getting back to this.
