### ISSUE TITLE
Support non-contiguous qubit indices

### ISSUE THREAD

**Issue by speller26** [amazon-braket/amazon-braket-default-simulator-python#252]
**Describe the feature you'd like**
The local simulator should support programs which use non-contiguous qubit indices, including cases where the qubit indices do not start from qubit 0.

Right now, the local simulator requires all qubits to be contiguous; in other words, an $n$-qubit circuit _must_ use exactly the qubits $0, 1, \ldots n - 1$, without omitting any or including any additional qubits:
```python
from braket.circuits import Circuit
from braket.devices import LocalSimulator

# Won't run
circuit = Circuit().h(2).cnot(2, 9)
LocalSimulator().run(circuit, shots=1000)
```

This constraint is unnecessary, and it would be worth modifying the default simulator implementation to allow arbitrary qubit indices, as in the above example.

**How would this feature be used? Please describe.**
This would allow users to test circuits on the local simulator before running them, unmodified, on a QPU. For example, without this feature, a circuit meant to run on a QPU with indices $2, 4, 7$ would first need to be modified to use qubits $0, 1, 2$ before it can be tested locally. This feature would also help prevent bugs that arise from translating qubit indices.

**Describe alternatives you've considered**
Qubits could be mapped manually, but this is unnecessarily complicated.

**Comment by rmshaffer** [comment]
PR https://github.com/amazon-braket/amazon-braket-default-simulator-python/pull/237 contains a possible approach to implementing this in the local simulator.

**Comment by rmshaffer** [comment]
Just a note @AbdullahKazi500 - issues for unitaryHACK should only be assigned after the corresponding PR is accepted and merged. Feel free to continue to work on the PR in the meantime!

**Comment by speller26** [comment]
The idea of this issue is to modify the simulator (namely, the [BaseLocalSimulator](https://github.com/amazon-braket/amazon-braket-default-simulator-python/blob/a4d7f98cb123ae6a1092972e728d2dbb93cb27b5/src/braket/default_simulator/simulator.py#L122)) to support non-contiguous qubits. Adding that support will automatically enable the LocalSimulator to run such circuits (rather than modifying the initializer of the LocalSimulator class).

**Comment by WingCode** [comment]
I would like to submit my PR.
